### ISSUE TITLE
Improvements in the setup.sh file

### ISSUE THREAD

**Issue by dalonsoa** [alan-turing-institute/binderhub-deploy#13]
On going testing of the `setup.sh` file (running on Mac OS):

- Brew is launched without checking if the packages are already installed (although brew itself checks this). 
- "echo WAHTEVER" could be added after each step to have an idea on the progress and know when things get stuck, if they do. Potentially including the total number of steps remaining Step 1/18, Step 2/18, etc.
-  There should be a warning in those steps that are known to take some time to complete, so people to get restless.

**Comment by sgibson91** [comment]
cc'd @tmbgreaves

**Comment by tmbgreaves** [comment]
Good ideas, thanks! Not checking the packages was mostly intentional to keep things simple -- is it likely to be a problem?

**Comment by dalonsoa** [comment]
Not at all! It just surprised me brew updating and trying to install things when I had everything installed already. Not a big deal: brew knows. Not sure if in other OS it might be more problematic.

**Comment by tmbgreaves** [comment]
Addressing these in https://github.com/tmbgreaves/binderhub-deploy/tree/address-issues-from-diego

**Comment by tmbgreaves** [comment]
Addressing package installs:

https://github.com/tmbgreaves/binderhub-deploy/commit/53148f5266034f99d31a6fca31a41f5401bfd2c9

**Comment by tmbgreaves** [comment]
Addressing user information:
https://github.com/tmbgreaves/binderhub-deploy/commit/ca064b2b1e75fe262f70b7f193434eaacc98b7f3

**Comment by dalonsoa** [comment]
Looks really good! Left a couple of comments in the commit.
