### ISSUE TITLE
Syntax error getting the nodes

### ISSUE THREAD

**Issue by dalonsoa** [alan-turing-institute/binderhub-deploy#15]
https://github.com/alan-turing-institute/binderhub-deploy/blob/ff03efd6594ee6c4cc80d98b7dcdb1e2c8a43f6f/setup.sh#L157

Thew first command should be `kubectl get nodes` with an `s` at the end. Otherwise, the command never finishes.

**Comment by sgibson91** [comment]
cc'd @tmbgreaves

**Comment by sgibson91** [comment]
`get nodes` and `get node` are interchangeable

**Comment by dalonsoa** [comment]
It seems it also works with `node` in singular. In any case, it seems that there's something weird in that command because it never ends.

**Comment by tmbgreaves** [comment]
Thanks @dalonsoa -- I guess perhaps the one node cluster has caused this to fail? I didn't test with that; I'll do so now :-)
