### ISSUE TITLE
Check jq bash parser correctly parses locations with spaces

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#17]
Locations can be parsed in one of two ways:
```
az group create --location "West Europe"
```
or:
```
az group create --location westeurope
```

We need to check that the `jq` bash parser for json handles these cases identically.

cc: @tmbgreaves

**Comment by dalonsoa** [comment]
If `s` is the location as read from JSON, then `${s//[[:blank:]]/} | tr '[:upper:]' '[:lower:]'` should do the job. I think.

**Comment by dalonsoa** [comment]
I can add this myself, but @tmbgreaves is massively changing this file, so it might be worth to let him change it.

**Comment by dalonsoa** [comment]
In the end I've made the change myself in #24 .
