### ISSUE TITLE
jp bash parser fails silently if config.json is not correct

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#23]
Need to add a test to `deploy.sh` to check `config.json` for errors.

cc: @tmbgreaves

**Comment by tmbgreaves** [comment]
Addressed in PR #22, commit https://github.com/alan-turing-institute/binderhub-deploy/pull/22/commits/4d686c6e8340f4bd342a1e92551d61d0863cb444

I've added some checks for the minimum set of variables to be correctly read in from the configuration file.

**Comment by tmbgreaves** [comment]
I'm in a big quandary over whether to add in the linter or not. In favour, it would be good to actually check the config file and tell a user where any errors are. On the other hand, it puts the linter dependency on us plus javascript, and we already have checks in place to make sure that the config we *need* has been read in correctly.

**Comment by sgibson91** [comment]
If our tests fail reliably and produce useful error messages, then I don't see a need to add in an extra dependency.

**Comment by tmbgreaves** [comment]
Let's leave it out then :-) It's been generating useful errors for me when I've made genuine mistakes and messed up my config...
