### ISSUE TITLE
Container deployments need to export secrets

### ISSUE THREAD

**Issue by tmbgreaves** [alan-turing-institute/binderhub-deploy#27]
When building using a container, secrets need to be either exported into the local filesystem (container run locally) or pushed to a keyvault (container run through blue button).

**Comment by sgibson91** [comment]
In the local scenario, the secrets would be output in `config.yaml` and `secret.yaml` yes? So it's just saving those files to the local system?

Keyvault is definitely the best option for automation.

**Comment by tmbgreaves** [comment]
Those, plus the ssh keys generated by aks create, I think

**Comment by sgibson91** [comment]
They should save to `~/.ssh/` though?

**Comment by tmbgreaves** [comment]
Resolved in PR #22 -- at the end of the deployment, the deploy script creates a storage account in the working resource group, then pushes logs. yamls, and the ssh keys to a blob.
