### ISSUE TITLE
Bug parsing resource group in teardown.sh

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#31]
There's a parsing issue in `teardown.sh`: 
`Resource group 'binderhub-deploy-test' could not be found.`

I think it needs to look for `binderhub-deploy-test_RG`.

I'd also like that script to be a bit more verbose in what it's doing.

**Comment by tmbgreaves** [comment]
Fixed in PR #22 , https://github.com/alan-turing-institute/binderhub-deploy/pull/22/commits/376f3911089d67182c92c0cfef42bb28abc5f8b7
