### ISSUE TITLE
Case flattening problem parsing subscription name in deploy.sh

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#32]
Subscription name "Azure Pass - Sponsorship" is parsed to ` az account set -s ${subscription}` in `deploy.sh` as "azure pass - sponsorship" throwing an error that the subscription could not be found. Current work-around is to use the hex-string subscription ID instead, but script should accept both.

**Comment by sgibson91** [comment]
![Screenshot 2019-05-30 at 10 51 40](https://user-images.githubusercontent.com/44771837/58624905-38883a00-82c9-11e9-900a-732da595171c.png)

Case flattening may be coming from the azure CLI itself!

**Comment by tmbgreaves** [comment]
I think we've been looking at this the wrong way, and it might be a problem with an uncaught login failure. I can get successful account sets with upper or lower case on the command line, but can get the error message as above if I run 'az logout' then re-run the account set.

**Comment by sgibson91** [comment]
Agreed. I think my screenshot came from a poorly-configured portal login.
