### ISSUE TITLE
Automated Builds on Docker Hub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#45]
DockerHub's docs on autobuilds: https://docs.docker.com/docker-hub/builds/

Rebuild master branch only (?)

I'd like the image to go under the `turinginst` DockerHub organisation. Need to check that I have access and update the ARM template to pull from there.

### Update

`binderhub-setup` container on DockerHub (builds): https://cloud.docker.com/repository/docker/sgibson91/binderhub-setup/builds

**Comment by sgibson91** [comment]
Dockerfile currently being autobuilt and pushed to `sgibson91/binderhub-setup:latest` from `master` branch.

**Comment by sgibson91** [comment]
Struggling to get the release v1.0 to be auto-built by DockerHub. Also latest tags from master began hanging. Tried deleting and recreating the DockerHub registry but that didn't seem to help. DockerHub server down maybe?

**Comment by sgibson91** [comment]
Took 15 hours but latest tag finally started building again! Must have been a Docker-side issue.

Regex expression `/^v([0-9.]+)$/` still not working to automatically build version tags. This is stumping me 🤷‍♀

**Comment by sgibson91** [comment]
So, it seems that DockerHub does **not** retroactively build version releases before the auto-build rule is set. A new tag `v1.0.2` successfully triggered the auto-build rule. Fingers crossed this continues to work 🤞 It may also be the case that auto-builds are only triggered from **git push** commands, _not_ just by creating a tag on the UI. This will need further testing.

**Comment by trallard** [comment]
Would this mean creating the tag from the CLI and then push? 
🤔 It sounds a bit weird not working from the creation of tags in the UI

**Comment by sgibson91** [comment]
Yes, I believe so. I'm finding the whole auto-build with Docker Hub experience a bit weird tbh!
