### ISSUE TITLE
A test suite for this repo?

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#54]
Does anyone have ideas for tests (to run on CI) for this repo?

**Comment by trallard** [comment]
Yes... can do that as part of me finishing the tutorial for integrating Continuous delivery - can do that next week that I am back in the UK or in transit

**Comment by sgibson91** [comment]
* Going to add basic checking of scripts with: https://github.com/koalaman/shellcheck
* Also use Travis to run `setup.sh` on multiple OS's
