### ISSUE TITLE
Issue with Helm

### ISSUE THREAD

**Issue by agahkarakuzu** [alan-turing-institute/binderhub-deploy#63]
Hi there! 

I am playing around with my Free Trial account on Azure to deploy a BinderHub instance. Everything goes smoothly till the Helm installation. I run into the following error: 

```
Error: failed to download "jupyterhub/binderhub" (hint: running `helm repo update` may help)
```

I passed the latest BinderHub version from the helm chart (`binderhub-0.2.0-8f31091`) to the env vars for the container.  I am following the route for deploying using the deploy button and filling out the form. I'd be glad if you can help me out 🙏 

 Thank you for putting this repo together, really useful!

**Comment by sgibson91** [comment]
Hi @agahkarakuzu, welcome! I'm sorry you're having problems, but _thank you_ for opening an issue! Would you mind finding out which Docker image tag the button is trying to run for me? On the button form, this will be the very last box, and is the image is called something like `sgibson91/binderhub-setup:<TAG>`. This will help me track down the bug 🙂

**Comment by agahkarakuzu** [comment]
Thanks @sgibson91! The version was 1.0.3. Sending this from mobile, so it is off the top of my head, but it was the latest version available on the dropdown list.

**Comment by sgibson91** [comment]
Awesome, thank you. I'll look into this tonight!

**Comment by sgibson91** [comment]
Ok, I had a spare 5mins to test the button and I couldn't reproduce this error. When you say you're using version `binderhub-0.2.0-8f31091`, are you parsing that whole string? Because it only needs the `0.2.0-8f31091` part. Can you try again using that please? Thank you!

**Comment by agahkarakuzu** [comment]
I think I passed version tag and the hash only, but will give it another try for good measure and let you know!

**Comment by sgibson91** [comment]
Thanks. If it crops up again, could you copy as much of the traceback as possible and make sure any secrets are removed? 👾 🐛

**Comment by agahkarakuzu** [comment]
Hey @sgibson91, I managed to successfully deploy it! I probably messed up something yesterday repeatedly for the Helm version :man_facepalming: . Thank you so much for your guidance and this amazing work! :confetti_ball:

**Comment by sgibson91** [comment]
AMAZING! 🎉I'm so pleased! Have fun BinderHub-ing and please feel free to come back with any other questions! 😊
