### ISSUE TITLE
[BUG] setup.sh doesn't actually run on Windows in Travis

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#75]
Currently, all tests pass - but I suspect that setup.sh on Windows is not actually running as there's no output as expected.

See the following job as an example:

* Main job: https://travis-ci.com/alan-turing-institute/binderhub-deploy/builds/142045473
  * Linux sub-job: https://travis-ci.com/alan-turing-institute/binderhub-deploy/jobs/269617004#L167
  * OSX sub-job: https://travis-ci.com/alan-turing-institute/binderhub-deploy/jobs/269617005#L179
  * Windows sub-job: https://travis-ci.com/alan-turing-institute/binderhub-deploy/jobs/269617006#L27

Maybe swap to GitHub actions?

**Comment by sgibson91** [comment]
@tallamjr do you know anything about running bash scripts on Windows VMs in Travis? Or, did you run GitHub actions on Windows at the DevOps workshop? If so, what was your experience? Thanks!

**Comment by tallamjr** [comment]
Hi @sgibson91 . I do not have experience with working with Windows on TravisCI, but at the DevOps workshop I found Github Actions worked very well across macOS, ubuntu and Windows..

It was later decided to not bother with Windows, but when initially experimenting with a Windows specific setup, I did something like this where I explicitly say I want to use `bash`:
```
      - name: Install (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
            <bash commands here> ..
```
Where the above being inspired by this [workflow/action](https://github.com/onqtam/doctest/blob/master/.github/workflows/main.yml)

Hope this is helpful 🤞

**Comment by sgibson91** [comment]
So after some playing around with GitHub Actions, I've discovered two things:

- The VMs available via GitHub Actions come with [preinstalled software](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners) which means testing installation scripts (in this case, `setup.sh`) is pretty much pointless with Actions
- Also, `setup.sh` doesn't appear to run on windows due to the following top-level condition, which means the windows case is never actually caught.

```bash
if [[ ${OSTYPE} == 'linux'* ]] ; then
    ...
elif [[ ${OSTYPE} == 'darwin'* ]] ; then
    ...
fi
```

**Comment by sgibson91** [comment]
### Update on PR #79 

I'm finding it difficult to test the `setup.sh` script for Windows. Spinning up a Windows VM on Azure and getting a command line to it is proving more difficult than originally anticipated. If anyone has a windows machine and is willing to experiment with the [chocolatey](https://chocolatey.org/) and [scoop](https://scoop.sh/) package managers for installing [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest), [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-windows) and [helm](https://helm.sh/docs/intro/install/#from-chocolatey-windows), your help would be much appreciated!
