### ISSUE TITLE
Support for Binder 2.0?

### ISSUE THREAD

**Issue by casperOne** [alan-turing-institute/binderhub-deploy#84]
First, I want to say thank you for this project; I had wanted to set up a binder instance for a long time in Azure, but didn't have the knowledge of k8s to do it (despite the fantastic getting started guide on the binder site).

That said, I was able to get a binder instance up and running in Azure.  Fantastic.

I may be mistaken, but it doesn't look like this supports binder 2.0.

If this is the case, is there a way to enable support that I can pursue on my own, or are there plans to update the "Deploy to Azure" button?

Thanks again for a fantastic resource.

**Comment by sgibson91** [comment]
Hi, thank you so much for stopping by! I'm so glad you've found this project useful.

Can you provide a bit more explanation around what you mean around 'binder 2.0' please? As far as I'm aware, any helm chart version from [this link](https://jupyterhub.github.io/helm-chart/#development-releases-binderhub) should work (although I admit I haven't tried since the versioning system switched to version ever).

Could you maybe provide your input variables and the error/bug you're seeing (secrets redacted)? 

Thanks! 🎉🏵️

**Comment by casperOne** [comment]
@sgibson91 Apologies, I've figured it out.

Initially, I was putting this into my binder instance:

https://github.com/dotnet/interactive

And I was not getting the lab interface, instead, I got:

![image](https://user-images.githubusercontent.com/561862/74383818-ee46da80-4dbd-11ea-9a9d-50756a83d125.png)

However, what I was expecting was the same experience as when I click on their "launch binder" link from their [README](https://github.com/dotnet/interactive/blob/master/docs/NotebooksOnBinder.md):

https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=lab

Where I see:

![image](https://user-images.githubusercontent.com/561862/74382695-da9a7480-4dbb-11ea-96b3-9acc81e09f89.png)

Going back to my install, the "Path to a notebook file" stood out to me, and when I selected "URL" and populated it with "File", it worked!

So, I think I'm good for now.  I have a lot to learn around helm and trying to redploy instances after I fiddle with configs, but that's completely separate for this.

This is addressed, and thanks for responding!

**Comment by sgibson91** [comment]
So glad you figured it out 🎉 We are constantly trying to think of ways we could improve the UI/UX of the website and make selecting the interface more intuitive.

On the redeploy instances after updating configs note, use the [upgrade.sh script](https://github.com/alan-turing-institute/binderhub-deploy/blob/master/upgrade.sh) in this repository.
