### ISSUE TITLE
Add option to deploy logs to blob storage when running scripts locally

### ISSUE THREAD

**Issue by casperOne** [alan-turing-institute/binderhub-deploy#85]
I've run through this process using the "Deploy to Azure" button, and running the scripts locally against my Azure subscription.

It would be helpful, when running the scripts locally if there was an option when running `deploy.sh` and `update.sh` to store the logs in blob storage like it does when using the "Deploy to Azure" button.

**Comment by sgibson91** [comment]
I like this idea! ✨ It would be a case of adding another variable to this line.

https://github.com/alan-turing-institute/binderhub-deploy/blob/afc856b17b857c977a7a4268751d02270414cb64/deploy.sh#L552

Something like "if CONTAINER_MODE or PUSH_TO_BLOB" where `PUSH_TO-BLOB` is boolean. Then adding a new variable to `template-config.json` (I think top-level) and making sure `deploy.sh` reads it in correctly.

Are you interested in opening a PR @casperOne ?

**Comment by casperOne** [comment]
@sgibson91 done!
